apiVersion: v1
kind: BuildConfig
metadata:
  name: flask-git-demo-pipeline
  labels:
    app: flask-git-demo
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "flask-git-demo", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
  - type: GitHub
    github:
      secret: a04aabf8d0002f77
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
         node {
           stage('buildImage'){
             openshiftBuild(buildConfig: 'flask-git-demo', showBuildLogs: 'true')
           }
           stage('deployApplication'){
             openshiftDeploy(deploymentConfig: 'flask-git-demo')
           }
         }
